# Generated by Django 4.0.2 on 2022-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
